version: '3.4'

services:
  identityserver:
    image: img-identity-server
    build:
      context: .
      dockerfile: JobSity.ChatApp.IdentityServer/Dockerfile
    ports:
      - 5004:80
      - 5005:443
    depends_on:
      - db
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123*1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro

  api:
    image: img-api
    build:
      context: .
      dockerfile: JobSity.ChatApp.Api/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - db
      - seq
      - rab
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123*1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
  
  bot:
    image: img-bot
    build:
      context: .
      dockerfile: JobSity.ChatApp.Bot/Dockerfile
    depends_on:
      - db
      - seq
      - rab

  webapp:
    image: img-webapp
    build:
      context: .
      dockerfile: JobSity.ChatApp.WebApp/Dockerfile
    ports:
      - 5002:80
      - 5003:443
    depends_on:
      - identityserver
      - api
      - bot
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev123*1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - 1433:1433
    environment:
      SA_PASSWORD: "dev123*1"
      ACCEPT_EULA: "Y"

  seq:
    image: datalust/seq:latest
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 1GB
    volumes:
      - ~/.aspnet/datadrive:/data
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=http://seq
    labels:
      - traefik.backend=seq
      - traefik.docker.network=webapp
      - traefik.port=5341
  
  rab:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672